import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    color: "teal",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#333",
    backgroundColor: "white",
    color: "black",
    width: "100%",
    marginVertical: 8,
    padding: 12,
    borderRadius: 10,
    fontSize: 16,
  },
  submitBtn: {
    width: "100%",
    backgroundColor: "teal",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 6,
    marginBottom: 16,
  },
  text: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
  },
  filterContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 10,
  },
  filterBtn: {
    flex: 1,
    backgroundColor: "#1f1f1f",
    marginHorizontal: 4,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#444",
  },
  activeFilterBtn: {
    flex: 1,
    backgroundColor: "teal",
    marginHorizontal: 4,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  filterText: {
    color: "#ccc",
    fontSize: 15,
    fontWeight: "500",
  },
  activeFilterText: {
    color: "white",
    fontSize: 15,
    fontWeight: "600",
  },
  todoItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    padding: 15,
    marginVertical: 8,
    shadowColor: "white",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 4,
  },
  todoTextContainer: {
    flex: 1,
    paddingRight: 10,
  },
  todoTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  todoDescription: {
    color: "#aaa",
    fontSize: 14,
    marginTop: 3,
  },
  todoActions: {
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
});
